#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { aggregateToolPacks, legacyToolMapping } from "../dist/full/aggregated-tools.js";
import { fullToolNames, sideEffectingToolNames } from "../dist/full/full-tools.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const MANIFEST_PATH = path.join(ROOT, "openclaw.plugin.json");
const PACKAGE_PATH = path.join(ROOT, "package.json");
const CAPABILITY_PATH = path.join(ROOT, "docs", "CAPABILITY-MAP.md");
const MIGRATION_PATH = path.join(ROOT, "docs", "TOOL-MIGRATION-MAP.md");
const CHECK_ONLY = process.argv.includes("--check");

const names = [...new Set(fullToolNames)].sort();
if (names.length < 30 || names.length > 35) {
  throw new Error(`expected 30-35 aggregate tools, found ${names.length}`);
}
if (Object.keys(legacyToolMapping).length !== 284) {
  throw new Error(`expected 284 uniquely mapped legacy tools, found ${Object.keys(legacyToolMapping).length}`);
}

const readJson = (file) => JSON.parse(fs.readFileSync(file, "utf8"));
const stableJson = (value) => `${JSON.stringify(value, null, 2)}\n`;

const manifest = readJson(MANIFEST_PATH);
const packageJson = readJson(PACKAGE_PATH);
const toolMetadata = Object.fromEntries(names.map((name) => [
  name,
  sideEffectingToolNames.has(name)
    ? { optional: true, sideEffecting: true }
    : { optional: true },
]));

const nextManifest = {
  ...manifest,
  contracts: { ...(manifest.contracts ?? {}), tools: names },
  toolMetadata,
};
const nextPackage = { ...packageJson, tools_count: names.length };

const capabilityLines = [
  "# Yach IM Full capability map",
  "",
  "> Generated by `npm run tools:sync`. Do not edit manually.",
  "",
  `- Public aggregate tools: **${names.length}**`,
  `- Internal legacy capabilities: **${Object.keys(legacyToolMapping).length}**`,
  `- Aggregate tools with at least one write action: **${sideEffectingToolNames.size}**`,
  "",
  ...names.map((name) => `- \`${name}\` — pack: \`${aggregateToolPacks[name]}\`${sideEffectingToolNames.has(name) ? " — contains write actions" : ""}`),
  "",
];
const capabilityMap = capabilityLines.join("\n");

const migrationLines = [
  "# Yach IM Full tool migration map",
  "",
  "> Generated by `npm run tools:sync`. Do not edit manually.",
  "",
  `- Legacy capabilities mapped: **${Object.keys(legacyToolMapping).length}**`,
  `- Public aggregate tools: **${names.length}**`,
  "- Legacy `yach_*` descriptors are internal execution targets and are not registered publicly.",
  "",
  "| Legacy tool | Aggregate tool | Pack | Action | Parameter adapter |",
  "| --- | --- | --- | --- | --- |",
  ...Object.values(legacyToolMapping)
    .sort((left, right) => left.legacyName.localeCompare(right.legacyName))
    .map((entry) => `| \`${entry.legacyName}\` | \`${entry.aggregateName}\` | \`${entry.pack}\` | \`${entry.action}\` | \`${entry.parameterAdapter}\` |`),
  "",
];
const migrationMap = migrationLines.join("\n");

if (CHECK_ONLY) {
  if (stableJson(manifest) !== stableJson(nextManifest)) {
    throw new Error("openclaw.plugin.json is out of sync; run npm run tools:sync");
  }
  if (packageJson.tools_count !== names.length) {
    throw new Error("package.json tools_count is out of sync; run npm run tools:sync");
  }
  if (!fs.existsSync(CAPABILITY_PATH) || fs.readFileSync(CAPABILITY_PATH, "utf8") !== capabilityMap) {
    throw new Error("docs/CAPABILITY-MAP.md is out of sync; run npm run tools:sync");
  }
  if (!fs.existsSync(MIGRATION_PATH) || fs.readFileSync(MIGRATION_PATH, "utf8") !== migrationMap) {
    throw new Error("docs/TOOL-MIGRATION-MAP.md is out of sync; run npm run tools:sync");
  }
} else {
  fs.writeFileSync(MANIFEST_PATH, stableJson(nextManifest));
  fs.writeFileSync(PACKAGE_PATH, stableJson(nextPackage));
  fs.mkdirSync(path.dirname(CAPABILITY_PATH), { recursive: true });
  fs.writeFileSync(CAPABILITY_PATH, capabilityMap);
  fs.writeFileSync(MIGRATION_PATH, migrationMap);
}

console.log(`[tool-registry] active=${names.length} unique=${new Set(names).size} sideEffecting=${sideEffectingToolNames.size}`);
