#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { fullToolNames, sideEffectingToolNames } from "../dist/full/full-tools.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const MANIFEST_PATH = path.join(ROOT, "openclaw.plugin.json");
const PACKAGE_PATH = path.join(ROOT, "package.json");
const CAPABILITY_PATH = path.join(ROOT, "docs", "CAPABILITY-MAP.md");
const CHECK_ONLY = process.argv.includes("--check");

const names = [...new Set(fullToolNames)].sort();
if (names.length !== 287) {
  throw new Error(`expected 287 unique migrated tools, found ${names.length}`);
}

const readJson = (file) => JSON.parse(fs.readFileSync(file, "utf8"));
const stableJson = (value) => `${JSON.stringify(value, null, 2)}\n`;

const manifest = readJson(MANIFEST_PATH);
const packageJson = readJson(PACKAGE_PATH);
const toolMetadata = Object.fromEntries(names.map((name) => [
  name,
  sideEffectingToolNames.has(name)
    ? { optional: true, sideEffecting: true }
    : { optional: true },
]));

const nextManifest = {
  ...manifest,
  contracts: { ...(manifest.contracts ?? {}), tools: names },
  toolMetadata,
};
const nextPackage = { ...packageJson, tools_count: names.length };

const capabilityLines = [
  "# Yach IM Full capability map",
  "",
  "> Generated by `npm run tools:sync`. Do not edit manually.",
  "",
  `- Active tools: **${names.length}**`,
  `- Optional tools: **${names.length}**`,
  `- Side-effecting tools requiring per-call approval: **${sideEffectingToolNames.size}**`,
  "",
  ...names.map((name) => `- \`${name}\`${sideEffectingToolNames.has(name) ? " — sideEffecting" : ""}`),
  "",
];
const capabilityMap = capabilityLines.join("\n");

if (CHECK_ONLY) {
  if (stableJson(manifest) !== stableJson(nextManifest)) {
    throw new Error("openclaw.plugin.json is out of sync; run npm run tools:sync");
  }
  if (packageJson.tools_count !== names.length) {
    throw new Error("package.json tools_count is out of sync; run npm run tools:sync");
  }
  if (!fs.existsSync(CAPABILITY_PATH) || fs.readFileSync(CAPABILITY_PATH, "utf8") !== capabilityMap) {
    throw new Error("docs/CAPABILITY-MAP.md is out of sync; run npm run tools:sync");
  }
} else {
  fs.writeFileSync(MANIFEST_PATH, stableJson(nextManifest));
  fs.writeFileSync(PACKAGE_PATH, stableJson(nextPackage));
  fs.mkdirSync(path.dirname(CAPABILITY_PATH), { recursive: true });
  fs.writeFileSync(CAPABILITY_PATH, capabilityMap);
}

console.log(`[tool-registry] active=${names.length} unique=${new Set(names).size} sideEffecting=${sideEffectingToolNames.size}`);
